# Second East Turkestan Republic
 country = { 
  tag       	 = REB
  
  nationalprovinces    = {  } 
  ownedprovinces       = {  } 
  controlledprovinces  = { 1273 1276 1280 } 
  capital	= 1981

  landunit = 
   {  location = 1280
     name     = "National Army of the Second East Turkestan Republic" 
     id       = {  type = 25600 id = 5  } 
     Division = 
     {  id   = {  type = 25600 id = 6 } 
       name = "Suidun-Ghulja-Kensai Regiments" 
       type = militia 
	   strength = 80 
	   model    = 4
      } 
     Division = 
     {  id   = {  type = 25600 id = 7  } 
       name = "Ghulja Reserve Regiment" 
       type = garrison
	   strength = 20
	   model    = 3
      } 
     Division = 
     {  id   = {  type = 25600 id = 8  } 
       name = "Tungan-Sibo-Mongol Regiments" 
       type = militia 
	   strength = 80 
	   model    = 4
      }
	 Division = 
	 {  id   = {  type = 25600 id = 9  }
	   name = "Kazakh Cavalry Regiment"
	   type = cavalry
	   strength = 40
	   model = 6
	  }
    } 
	
}
 