### Additions by Kretoxian

province = {
	id = 333 # Skopje - Macedonia - Balkan
	air_base = { size = 2 current_size = 2 }
	anti_air = 2
}

province = {
	id = 330 # Niš - Southern Serbia - Balkan
	air_base = { size = 1 current_size = 1 }
}

province = {
	id = 349 # Ljubljana - Slovenia - Balkan
	air_base = { size = 1 current_size = 1 }
}

province = {
	id = 356 # Mostar - Bosnia - Balkan
	air_base = { size = 2 current_size = 2 }
	anti_air = 2
}

province = {
	id = 355 # Sarajevo - Bosnia - Balkan
	air_base = { size = 2 current_size = 2 }
	anti_air = 2
}