### USSR hero cities

province = { id = 247 ic = 1 }
province = { id = 553 ic = 2 }
province = { id = 663 ic = 2 }
province = { id = 626 ic = 1 }
province = { id = 641 ic = 1 }
province = { id = 572 ic = 3 }
province = { id = 617 ic = 1 }
province = { id = 694 ic = 1 }
province = { id = 640 ic = 1 }
province = { id = 599 ic = 1 }
province = { id = 584 ic = 1 }
province = { id = 535 ic = 1 }
province = { id = 589 ic = 1 }
province = { id = 668 ic = 1 }
province = { id = 1191 ic = 1 }
