# Rocket and Nuclear sites

# Oxford - ENG (Dido Reactor)
province = {
	id = 28
	nuclear_reactor = 1
}

# Arzamas - SOV (Arzamas-16)
province = {
	id = 683
	nuclear_reactor = 1
}

# Nelidovo - SOV (Gorodomlya Island)
province = {
	id = 577
	rocket_test = 3
}

# Albuquerque - USA (Los Alamos)
province = {
	id = 1904
	nuclear_reactor = 6
}

# Jacksonville - USA (White Sands Proving Grounds)
province = {
	id = 1904
	rocket_test = 3
}