province = { id = 1172 points = 2 } #Jerusalem
province = { id = 1199 points = 1 } #Harbin
province = { id = 1534 points = 1 } #Rawalpindi/Islamabad
province = { id = 1540 points = 1 } #Srinagar
province = { id = 1654 points = 1 } #Jogjakarata
province = { id = 1653 points = 1 } #Soerabaja
province = { id = 1227 points = 1 } #Haemhung
province = { id = 1232 points = 1 } #Busan
province = { id = 1438 points = 1 } #Kuala Lumpur
province = { id = 1500 points = 1 } #Madras
province = { id = 1445 points = 1 } #Dhaka

### Soviet Union hero cities

province = { id = 247 points = 1 } # Brest
province = { id = 553 points = 5 } # Leningrad
province = { id = 663 points = 4 } # Stalingrad
province = { id = 626 points = 1 } # Odessa
province = { id = 641 points = 2 } # Sevastopol
province = { id = 572 points = 10 } # Moscow
province = { id = 617 points = 2 } # Kiev
province = { id = 694 points = 1 } # Novorossiysk
province = { id = 640 points = 1 } # Kerch
province = { id = 599 points = 2 } # Minsk
province = { id = 584 points = 1 } # Tula
province = { id = 535 points = 2 } # Murmansk
province = { id = 589 points = 1 } # Smolensk