### Additions by Kretoxian

province = {
	id = 333 # Skopje - Macedonia - Balkan
	air_base = { size = 5 current_size = 5 }
	anti_air = 5
}

province = {
	id = 330 # Niš - Southern Serbia - Balkan
	air_base = { size = 1 current_size = 1 }
}

province = {
	id = 349 # Ljubljana - Slovenia - Balkan
	air_base = { size = 3 current_size = 3 }
	anti_air = 3
}

province = {
	id = 356 # Mostar - Bosnia - Balkan
	air_base = { size = 2 current_size = 2 }
	anti_air = 2
}

province = {
	id = 355 # Sarajevo - Bosnia - Balkan
	air_base = { size = 2 current_size = 2 }
	anti_air = 2
}
province = {
	id = 352 # Zagreb - Croatia - Balkan
	air_base = { size = 4 current_size = 4 }
	anti_air = 4
}

province = {
	id = 349 # Ljubljana - Slovenia - Balkan
	air_base = { size = 1 current_size = 1 }
}

province = {
	id = 347 #Karlovac - Croatia - Balkan
	air_base = { size = 1 current_size = 1 }
}

province = {
	id = 332 # Cetinje - West Serbia - Balkan
	naval_base = { size = 3 current_size = 3 }
}

province = {
	id = 338 # Belgrade - Central Serbia - Balkan
	anti_air = 3
	air_base = { size = 6 current_size = 6 }
}

province = {
	id = 343 # Dubrovnik - Croatia - Balkan
	anti_air = 2
}

province = {
	id = 350 # Split - Croatia - Balkan
	anti_air = 2
	air_base = { size = 2 current_size = 2 }
	naval_base = { size = 3 current_size = 3 }
}