# Rocket and Nuclear sites

# Carlisle - ENG (RAF Spadeadam)
province = {
	id = 14
	rocket_test = 2
}

# Oxford - ENG (Dido Reactor)
province = {
	id = 28
	nuclear_reactor = 7
}

# Paris - FRA (Reactor Zoé)
province = {
	id = 55
	nuclear_reactor = 4
}

# Stuttgart - DFR (Lampoldshausen)
province = {
	id = 134
	rocket_test = 1
}

# Hamburg - DFR (Helmholtz-Zentrum Geesthacht)
province = {
	id = 154
	nuclear_reactor = 1
}

# Milan - ITA (CeSNEF L-54: Milano Technical University)
province = {
	id = 407
	nuclear_reactor = 1
}

# Arzamas - SOV (Arzamas-16)
province = {
	id = 683
	nuclear_reactor = 9
}

# Colom-Bechar - FRA (Hammaguir)
province = {
	id = 739
	rocket_test = 5
}

# Kyzyl-Orda - SOV (Baikonur)
province = {
	id = 1110
	rocket_test = 10
}

# Lanzhou - CHC (Lanzhou Diffusion Enrichment Facility)
province = {
	id = 1264
	nuclear_reactor = 2
}

# Bayan-Hot - CHC (Base 20)
province = {
	id = 1272
	rocket_test = 1
}

# Madurai - IND (Liquid Propulsion Systems Centre)
province = {
	id = 1504
	rocket_test = 1
}

# Bombay - IND (CIRUS Reactor at Bhabha Atomic Research Center)
province = {
	id = 1517
	nuclear_reactor = 1
}

# Sendai - JAP (Tokai JRR-1 Japan Research Reactor No. 1)
province = {
	id = 1549
	nuclear_reactor = 1
}

# Albuquerque - USA (Los Alamos)
province = {
	id = 1904
	nuclear_reactor = 9
}

# Jacksonville - USA (Cape Canaveral)
province = {
	id = 1949
	rocket_test = 10
}

# Stockholm - SWE (R1)
province = {
	id = 2159
	nuclear_reactor = 1
}
