# Reykjavik

province = {
	id = 1
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# London

province = {
	id = 29
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Dublin

province = {
	id = 34
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Paris

province = {
	id = 55
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Luxembourg

province = {
	id = 109
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Brussels

province = {
	id = 116
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Amsterdam

province = {
	id = 122
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Cologne

province = {
	id = 131
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Berlin

province = {
	id = 163
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Vienna

province = {
	id = 195
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Prague

province = {
	id = 207
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Warsaw

province = {
	id = 232
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Budapest

province = {
	id = 284
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Copenhagen

province = {
	id = 294
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Bucharest

province = {
	id = 316
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Sofia

province = {
	id = 321
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Belgrade

province = {
	id = 338
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Tirana

province = {
	id = 359
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Athens

province = {
	id = 377
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Bern

province = {
	id = 392
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Rome

province = {
	id = 419
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Madrid

province = {
	id = 460
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Lisbon

province = {
	id = 476
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Oslo

province = {
	id = 483
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Helsinki

province = {
	id = 525
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Moscow

province = {
	id = 572
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Rabat

province = {
	id = 717
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Cairo

province = {
	id = 787
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Khartoum

province = {
	id = 810
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Addis Adeba

province = {
	id = 825
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Mogadishu

province = {
	id = 836
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Nairobi

province = {
	id = 841
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Kampala

province = {
	id = 844
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Dar es Salaam

province = {
	id = 850
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Lourenco Marques

province = {
	id = 855
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Salisbury

province = {
	id = 867
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Pretoria

province = {
	id = 873
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Luanda

province = {
	id = 895
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Leopoldville

province = {
	id = 899
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Brazzaville

province = {
	id = 907
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Yaounde

province = {
	id = 909
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Libreville

province = {
	id = 915
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Fort Lamy

province = {
	id = 920
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Bangui

province = {
	id = 926
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Lagos

province = {
	id = 929
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Niamey

province = {
	id = 944
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Lome

province = {
	id = 950
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Cotonou

province = {
	id = 951
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Accra

province = {
	id = 956
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Ouagadougou

province = {
	id = 957
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Abidjan

province = {
	id = 962
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Freetown

province = {
	id = 964
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Conakry

province = {
	id = 966
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Monrovia

province = {
	id = 969
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Bamako

province = {
	id = 976
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Dakar

province = {
	id = 978
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Banjul

province = {
	id = 979
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Nouakchott

province = {
	id = 981
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Tel Aviv

province = {
	id = 1008
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Damascus

province = {
	id = 1016
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Beirut

province = {
	id = 1019
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Amman

province = {
	id = 1022
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Baghdad

province = {
	id = 1034
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Doha

province = {
	id = 1038
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Kuwait

province = {
	id = 1041
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Riyadh

province = {
	id = 1045
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Sanaa

province = {
	id = 1050
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Ankara

province = {
	id = 1075
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Teheran

province = {
	id = 1085
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Ulaanbaatar

province = {
	id = 1124
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Jerusalem

province = {
	id = 1172
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Pyeongyang

province = {
	id = 1221
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Seoul

province = {
	id = 1228
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Beijing

province = {
	id = 1247
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Lhasa

province = {
	id = 1289
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Taipei

province = {
	id = 1362
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Hanoi

province = {
	id = 1395
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Phnom Penh

province = {
	id = 1400
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Vientiane

province = {
	id = 1405
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Rangoon

province = {
	id = 1415
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Bangkok

province = {
	id = 1423
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Singapore

province = {
	id = 1432
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Kuala Lumpur

province = {
	id = 1438
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Punakha

province = {
	id = 1456
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Kathmandu

province = {
	id = 1457
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Delhi

province = {
	id = 1459
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Colombo

province = {
	id = 1511
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Karachi

province = {
	id = 1533
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Tokyo

province = {
	id = 1552
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Manila

province = {
	id = 1565
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Kuching

province = {
	id = 1624
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Bandar Seri Begawan

province = {
	id = 1625
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Batavia

province = {
	id = 1647
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Canberra

province = {
	id = 1707
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Wellington

province = {
	id = 1721
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Trinidad

province = {
	id = 1758
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Havana

province = {
	id = 1776
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Ciudad Trujillo

province = {
	id = 1780
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Port-au-Prince

province = {
	id = 1781
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Jamaica

province = {
	id = 1782
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Washington

province = {
	id = 1809
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Mexico City

province = {
	id = 1974
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Medellin

province = {
	id = 1987
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Caracas

province = {
	id = 1993
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Lima

province = {
	id = 2016
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Nuestra Senora de La Paz

province = {
	id = 2020
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Santiago de Chile

province = {
	id = 2023
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# San Francisco de Quito

province = {
	id = 2042
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Villa Hayes

province = {
	id = 2046
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Buenos Aires

province = {
	id = 2050
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Montevideo

province = {
	id = 2052
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Rio de Janeiro

province = {
	id = 2075
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Ciudad de Panama

province = {
	id = 2078
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# San Salvador

province = {
	id = 2079
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Managua

province = {
	id = 2080
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# San Jose

province = {
	id = 2081
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Tegucigalpa

province = {
	id = 2085
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Ciudad de Guatemala

province = {
	id = 2088
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Pembroke

province = {
	id = 2113
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Stockholm

province = {
	id = 2159
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
# Kabul

province = {
	id = 2171
	ic = 2
	energy = 4
	metal = 2
	rare_materials = 1
	manpower = 1
}
