# Rocket and Nuclear sites

# Oxford - ENG (Dido Reactor)
province = {
	id = 28
	nuclear_reactor = 4
}

# Paris - FRA (Reactor Zoé)
province = {
	id = 55
	nuclear_reactor = 2
}

# Arzamas - SOV (Arzamas-16)
province = {
	id = 683
	nuclear_reactor = 6
}

# Colom-Bechar - FRA (Hammaguir)
province = {
	id = 739
	rocket_test = 2
}

# Nelidovo - SOV (Gorodomlya Island)
province = {
	id = 577
	rocket_test = 5
}

# Albuquerque - USA (Los Alamos)
province = {
	id = 1904
	nuclear_reactor = 7
}

# Jacksonville - USA (White Sands Proving Grounds)
province = {
	id = 1904
	rocket_test = 3
}
