# Australia: Populate or perish

province = {
	id = 1705
	manpower = 1.87
}

province = {
	id = 1707
	manpower = 1.87
}

province = {
	id = 1708
	manpower = 1.87
}

# Canada: New oil fields

province = {
	id = 2103
	oil = 2
}

province = {
	id = 2104
	oil = 2
}

### USSR hero cities

province = { id = 247 ic = 1 }
province = { id = 553 ic = 2 }
province = { id = 663 ic = 2 }
province = { id = 626 ic = 1 }
province = { id = 641 ic = 1 }
province = { id = 572 ic = 3 }
province = { id = 617 ic = 1 }
province = { id = 694 ic = 1 }
province = { id = 640 ic = 1 }
province = { id = 599 ic = 1 }
province = { id = 584 ic = 1 }
province = { id = 535 ic = 1 }
province = { id = 589 ic = 1 }
province = { id = 668 ic = 1 }
province = { id = 1191 ic = 1 }
