# Rocket and Nuclear sites

# Oxford - ENG (Dido Reactor)
province = {
	id = 28
	nuclear_reactor = 6
}

# Paris - FRA (Reactor Zoé)
province = {
	id = 55
	nuclear_reactor = 3
}

# Arzamas - SOV (Arzamas-16)
province = {
	id = 683
	nuclear_reactor = 7
}

# Colom-Bechar - FRA (Hammaguir)
province = {
	id = 739
	rocket_test = 4
}

# Nelidovo - SOV (Gorodomlya Island)
province = {
	id = 577
	rocket_test = 8
}

# Albuquerque - USA (Los Alamos)
province = {
	id = 1904
	nuclear_reactor = 8
}

# Jacksonville - USA (Joint Long Range Proving Grounds)
province = {
	id = 1949
	rocket_test = 7
}

# Milan - ITA (CeSNEF L-54)
province = {
	id = 407
	nuclear_reactor = 1
}
