##############################
# Country definition for UCH #
##############################

 
 ##################### 
 # Country main data # 
 ##################### 

 country = 
 { 
	tag					= UCH
	capital				= 1247 # Beijing
	ai					= "UCH_1914.ai"
	ai_settings			= { flags = { MOB1 = yes MOB2 = yes MOB3 = yes MOB4 = yes } }
	
	# Resource Reserves 
	energy                 = 4860
	metal                  = 2430
	rare_materials         = 1215
	oil       			   = 1000  
	supplies    	       = 1000  
	money      			   = 10  
	manpower      		   = 200
	dissent        		   = 10
	transports       	   = 110  
	escorts        		   = 2  
 diplomacy =
 { 
	relation = {   tag = JAP value = -25  }   
	relation = {   tag = ENG value = 75   }   
	relation = {   tag = FRA value = 50   }   
	relation = {   tag = U08 value = 25   }
	relation = {   tag = RUS value = -25  }      
	relation = {   tag = U09 value = 25   }   
	relation = {   tag = U02 value = 50   }   
	relation = {   tag = TIB value = -25  }   
	relation = {   tag = MON value = -25  }   
	relation = {   tag = AST value = 25   }   
	relation = {   tag = USA value = 25   }   
	relation = {   tag = SIA value = 25   }   
	relation = {   tag = U03 value = 10   }   
	relation = {   tag = ITA value = 10   } 
	relation = {   tag = BHU value = 15   } 
	relation = {   tag = NEP value = 15   } 
	relation = {   tag = HOL value = 15   } 
	relation = {   tag = AFG value = 15   } 
 }
 headofstate            = {  type = 9 id = 1325100  }
 headofgovernment       = {  type = 9 id = 1325101  }
 foreignminister        = {  type = 9 id = 1325102  }
 armamentminister       = {  type = 9 id = 1325103  }
 ministerofsecurity     = {  type = 9 id = 1325105  }
 ministerofintelligence = {  type = 9 id = 1325104  }
 chiefofstaff           = {  type = 9 id = 1325106  }
 chiefofarmy            = {  type = 9 id = 1325107  }
 chiefofnavy            = {  type = 9 id = 1325108  }
 chiefofair             = {  type = 9 id = 1325109  }
 SpyInfo                = {  country = "UCH" NumberOfSpies = 2  } 
 nationalprovinces      = {
 # Nationalist China at Start 
 1333 1261 1303 1339 1323 1321 1334 1336 1340 1341 1319 1322 1324 1325 1326 1316 1317 1344 1342 1337 1338 1345 1346 1347 1348  1357 1358  1359 1360 1354  1353 1318 1355 1309  1311 1312 1310  1304   1302  1258 1262 1257  1296 1292 1293 1297 1298  1305 1306 1291 1313 1307  1308  1356  1349     1335    1314 1315    1267    1320   1299  1343  1300 1301 1350 1351 1352      
  
 # Yunnan
 1389 1390 1384 1385 1386 1387 1388 
  
 # Guanxi Clique  
  1378  1365  1376 1377 1375 1380 1381 1382 1383  1369 1370 1373  1379 1367 1374 1368  
  
 # Shanxi       
  1241 1247 1246 1251  1242 1254 1332  1252 1253 1248 1249 1250 1327 1243 1244 1245 1329 1330

 # German Concession
 1328
 
 # United Kingdom Concessions
 1331

 # Manchoukou 
 1202 1204 1212 1205 1199 1203 1200 1206 1213 1237 1207 1220 1218 1236 1201 1208 1209 1210 1211 1214 1215  1216 1235 1217 1197 1198   
  
 # Xibei san ma            
 1269 1268 1270 1271 1264 1263 1272 1265 1266 1283 1284 1285   
  
 # Tibet       
 1294 1290 1286 1287 1288 1289 1295 
  
 # Sinkiang        
 1273 1279 1280 1281 1277 1274 1275 1282 1276
  
 # India        
 1278
  
 # Communist China      
 1259 1260 1255 1256 
  
 # Japan In China     
 1219 1238 1240 1239 
  
 # European Possessions     
 1371 1372  
   
 # Taiwan     
 1361 1362 1363 1364   
  
 # Mongolia 
 1120 1124 1125 1123 1121 1122 
 
 # Additional Claims
 1414 1458 1413 1455
} 
 ownedprovinces         = {  
 # Nationalist China at start
 1356 1333 1261 1303 1339 1334 1336 1340 1341 1319 1322
 1324 1325 1326 1316 1317 1344 1342 1337 1338 1345 1346
 1347 1348 1357 1358 1359 1360 1354 1353 1318 1355 1309 
 1311 1312 1310 1304 1302 1296 1297 1298 1305 1306 1313
 1307 1308 1349 1335 1314 1315 1267 1320 1299 1343 1300
 1301 1350 1351 1352 1321 1323

 # Communist China
 1259 1260 1255
 
 # Shanxi
 1241 1247 1246 1251 1242 1254 1332 1252 1253 1248 1249
 1250 1327 1243 1244 1245 1329 1330

 # Manchoukou 
 1202 1204 1212 1205 1199 1203 1200 1206 1213 1237 1207
 1220 1218 1236 1201 1208 1209 1210 1211 1214 1215
 1216 1235 1217 1197 1198

 # Xi Bei/ Ma Clique
 1263 1256

 # Japan In China
 1238 1240 1239

 # Shanxi
 1258 1257
 }
 controlledprovinces    = {
 # Nationalist China at start
 1356 1333 1261 1303 1339 1334 1336 1340 1341 1319 1322
 1324 1325 1326 1316 1317 1344 1342 1337 1338 1345 1346
 1347 1348 1357 1358 1359 1360 1354 1353 1318 1355 1309 
 1311 1312 1310 1304 1302 1296 1297 1298 1305 1306 1313
 1307 1308 1349 1335 1314 1315 1267 1320 1299 1343 1300
 1301 1350 1351 1352 1321 1323

 # Communist China
 1259 1260 1255
 
 # Shanxi
 1241 1247 1246 1251 1242 1254 1332 1252 1253 1248 1249
 1250 1327 1243 1244 1245 1329 1330

 # Manchoukou 
 1202 1204 1212 1205 1199 1203 1200 1206 1213 1237 1207
 1220 1218 1236 1201 1208 1209 1210 1211 1214 1215
 1216 1235 1217 1197 1198

 # Xi Bei/ Ma Clique
 1263 1256

 # Japan In China     
 1238 1240 1239
 
 # Shanxi
 1258 1257
 }
 claimedprovinces = {
 # Japan
 1563 1562 1564
 }

 techapps               = { 
 #Infantry - Up to 1907
 1010 1020 1030

 #Cavalry - Up to 1897
 13060 13070
 
 #Light Infantry Division - Only 1870
 1160

 #Early Construction - Only 1870
 5800

 #Interwar Light Cruiser 
 3110
 #Early Heavy Cruiser
 3210
 #Early Battleship
 3410
 #Troopships
 3810
 #Early Torpedoes
 3720

 #Land Doctrines
 6500 6510

 #Naval Doctrines
 8010 8020 8050 8060 8070 81300

 #Air Doctrines
 }
 blueprints = {
 # Torpedo Gunboat (DD)
 3010
 
 # Scout Cruiser (CL)
 3120
 
 # 20th Century Land Doctrine
 6530
 }

 policy = 
  {
   date       = { year = 0 month = january day = 0   }  
   democratic    		= 2  
   political_left  		= 3  
   free_market			= 9  
   freedom      		= 3  
   professional_army 	= 4  
   defense_lobby     	= 8  
   interventionism  	= 4
  }
 dormant_leaders    = { 50368 55375 }
 # 1914 China OOB (Partially Extrapolated). Around 50 divisions in China total.
 # 23 Divisions were in Beiyang control.
 # Special thanks to research by Delanonne.
 # Wu-wei Jun: Based around Manchuria, Loyal to Yuan Shikai. Later joins the Zhili Clique under Cao Kun.
 landunit = 
 {
   location = 1247 # Beijing 
   name   = "Wu-wei Jun"  
#   leader = # Yuan Shikai 
   id    = {   type = 22000 id = 10000  }  
   Division = 
   {
    experience = 20
    id     = {   type = 22000 id = 10001   }  
    name    = "Frontal Division" #Led by Ma Yuekun
    type    = infantry  
    model   = 3
   }
   Division = 
   {
    experience = 20  
    id     = {   type = 22000 id = 10002   }  
    name    = "Left Division" #Led by Yuan Shikai
    type    = infantry  
    model   = 3  
   }
   Division = 
   {
    experience = 0
    id     = {   type = 22000 id = 10003   }  
    name    = "Hind Division" #Led by Nie Shicheng
    type    = infantry  
    model   = 2  
   }
   Division = 
   {
    experience = 0
    id     = {   type = 22000 id = 10004   }  
    name    = "Right Division" #Led by Dong Fuziang
    type    = infantry  
    model   = 2  
   }
   Division = 
   {
    experience = 0
    id     = {   type = 22000 id = 10005   }  
    name    = "Middle Division" #Led by Duang Zhigui
    type    = infantry  
    model   = 2  
   }
   Division = 
   {
    experience = 0
    id     = {   type = 22000 id = 10006   }  
    name    = "New Division" #Led by ???
    type    = infantry
    model   = 2
   }
   
 }
 # Huai-jun: Based in Hubei-Jiangsu. Loyal to local governors/Zhang Zhidong. Are NOT warlord troops. Jiangsu supported KMT.
 landunit = 
 {
   location = 1317 # Wuhan  
   name   = "Hubei Huai-jun"  
#   leader = # ??
   id    = {   type = 22000 id = 10010  }  
   Division = 
   {
    experience = 0
    id     = {   type = 22000 id = 10011   }  
    name    = "Hubei Lujun" #Led by ???
    type    = infantry  
    model   = 1
	locked = yes
   }
 }
 landunit = 
 {
   location = 1337 # Nanjing 
   name   = "Jiangsu Huai-jun"  
#   leader = # ??
   id    = {   type = 22000 id = 10020  }  
   Division = 
   {
    experience = 0
    id     = {   type = 22000 id = 10021   }  
    name    = "Jiangsu Lujun" #Led by ???
    type    = infantry  
    model   = 1
	locked = yes
   }
 }
 # Shanghai Bund: Based in Shanghai, Loyal to Sun Zhongshan and the KMT.
 landunit = 
 {
   location = 1338 # Shanghai 
   name   = "Shanghai Mingzhongjituan"  
#   leader = # Chen Qimei
   id    = {   type = 22000 id = 10030  }  
   Division = 
   {
    experience = 40
    id     = {   type = 22000 id = 10031   }  
    name    = "Shanghai Mingbin" #Led by Chen Qimei
    type    = militia
    model   = 0
	locked = yes
   }
 }
 # Jiangxi-jun: Based in Jiangxi. Loyal to local governors/Li Liejun. Are NOT warlord troops. Supported KMT.
 landunit = 
 {
   location = 1352 # Nanchang 
   name   = "Jiangxi Difangjun"  
#   leader = # ??
   id    = {   type = 22000 id = 10040  }  
   Division = 
   {
    experience = 0
    id     = {   type = 22000 id = 10041   }  
    name    = "Jiangxi Lujun" #Led by ???
    type    = infantry
    model   = 1
	locked = yes
   }
 }
 # Anhui: Loyal to Duan Qirui
 landunit = 
 {
   location = 1340 # Hefei
   name   = "Second Corps"  
#   leader = # Duan Qirui
   id    = {   type = 22000 id = 10050  }  
   Division = 
   {
    experience = 0
    id     = {   type = 22000 id = 10051   }  
    name    = "1st SC Division" #Led by ???
    type    = infantry  
    model   = 2
   }
   Division = 
   {
    experience = 0
    id     = {   type = 22000 id = 10052   }  
    name    = "2nd SC Division" #Led by ???
    type    = infantry  
    model   = 2
   }
   Division = 
   {
    experience = 0
    id     = {   type = 22000 id = 10053   }  
    name    = "3rd SC Division" #Led by ???
    type    = infantry  
    model   = 2  
   }
   Division = 
   {
    experience = 0
    id     = {   type = 22000 id = 10054   }  
    name    = "4th SC Division" #Led by ???
    type    = infantry  
    model   = 2  
   }
   Division = 
   {
    experience = 0
    id     = {   type = 22000 id = 10055   }  
    name    = "5th SC Division" #Led by ???
    type    = infantry  
    model   = 2  
   }
   Division = 
   {
    experience = 0
    id     = {   type = 22000 id = 10056   }  
    name    = "6th SC Division" #Led by ???
    type    = infantry
    model   = 2
   }
   
 }
 # Zhejiang (Extrapolated) Loyal to local governors/Tong Baoxuan. Are NOT warlord troops. Supported all factions except communists.
 landunit = 
 {
   location = 1345 # Hangzhou
   name   = "Zhejiang Difangjun"  
#   leader = # ??
   id    = {   type = 22000 id = 10060  }  
   Division = 
   {
    experience = 0
    id     = {   type = 22000 id = 10061   }  
    name    = "Zhejiang Lujun" #Led by ???
    type    = infantry
    model   = 1
	locked = yes
   }
 }
 # Sichuan, later joins Zhili Clique. (Extrapolated)
 landunit =
 {
   location = 1297 # Chendu
   name   = "Sichuan Difangjun"  
#   leader = # ??
   id    = {   type = 22000 id = 10070  }  
   Division = 
   {
    experience = 0
    id     = {   type = 22000 id = 10071   }  
    name    = "Sichuan Lujun" #Led by ???
    type    = infantry
    model   = 2
	locked = yes
   }
 }
 landunit =
 {
   location = 1299 # Chongqing
   name   = "Chongqing Mingzhongjituan"  
#   leader = # ??
   id    = {   type = 22000 id = 10080  }  
   Division = 
   {
    experience = 0
    id     = {   type = 22000 id = 10081   }  
    name    = "Congqing Mingbin" #Led by ???
    type    = militia
    model   = 0
	locked = yes
   }
 }
 # Shandong (Extrapolated)
 landunit =
 {
   location = 1330 # Jinan
   name   = "Shandong Renmingjun"  
#   leader = # ??
   id    = {   type = 22000 id = 10090  }  
   Division = 
   {
    experience = 0
    id     = {   type = 22000 id = 10091   }  
    name    = "1 Shangdong Mingbin" #Led by ???
    type    = militia
    model   = 0
	locked = yes
   }
   Division = 
   {
    experience = 0
    id     = {   type = 22000 id = 10092   }  
    name    = "2 Shangdong Mingbin" #Led by ???
    type    = militia
    model   = 0
	locked = yes
   }
 }
 # Fujian (Extrapolated)
 landunit =
 {
   location = 1360 # Xiamen
   name   = "Fujian Difangjun"  
#   leader = # ??
   id    = {   type = 22000 id = 10100  }  
   Division = 
   {
    experience = 0
    id     = {   type = 22000 id = 10101   }  
    name    = "Fujian Mingbin" #Led by ???
    type    = militia
    model   = 0
	locked = yes
   }
 }
 # Hunan (Extrapolated)
 landunit =
 {
   location = 1308 # Changsha
   name   = "Hunan Difangjun"  
#   leader = # ??
   id    = {   type = 22000 id = 10110  }  
   Division = 
   {
    experience = 0
    id     = {   type = 22000 id = 10111   }  
    name    = "Hunan Lujun" #Led by ???
    type    = infantry
    model   = 2
	locked = yes
   }
 }
 # Manchuria (Extrapolated) Warlord troops, loyal to Zhang Zuolin. Later led by Yan Xishan
 landunit =
 {
   location = 1199 # Harbin
   name   = "Dongbei Difangjun"  
#   leader = # Zhang Zuolin
   id    = {   type = 22000 id = 10120  }  
   Division = 
   {
    experience = 5
    id     = {   type = 22000 id = 10121   }  
    name    = "1 Dongbei Lujun" #Led by Zhang Zuolin
    type    = infantry
    model   = 1
	locked = yes
   }
   Division = 
   {
    experience = 5
    id     = {   type = 22000 id = 10122   }  
    name    = "2 Dongbei Lujun" #Led by ???
    type    = infantry
    model   = 1
	locked = yes
   }
   Division = 
   {
    experience = 5
    id     = {   type = 22000 id = 10123   }  
    name    = "3 Dongbei Lujun" #Led by ???
    type    = infantry
    model   = 1
	locked = yes
   }
 }
 # Guizhou (Extrapolated) Loyal to Tang Jiyao/NPA.
 landunit =
 {
   location = 1305 # Guiyang
   name   = "Guizhou Difangjun"  
#   leader = # Tang Jiyao
   id    = {   type = 22000 id = 10130  }  
   Division = 
   {
    experience = 5
    id     = {   type = 22000 id = 10131   }  
    name    = "Guizhou Lujun" #Led by Tang Jiyao
    type    = infantry
    model   = 2
	locked = yes
   }
 }
 # Shanxi (Extrapolated)
 landunit =
 {
   location = 1252 # Taiyuan
   name   = "Shanxi Mingzhongjituan"  
#   leader = # ???
   id    = {   type = 22000 id = 10140  }  
   Division = 
   {
    experience = 5
    id     = {   type = 22000 id = 10141   }  
    name    = "Shanxi Mingbin" #Led by ???
    type    = militia
    model   = 1
	locked = yes
   }
 }
 # Shaanxi (Extrapolated)
 landunit =
 {
   location = 1258 # Xi'an
   name   = "Shaanxi Mingzhongjituan"  
#   leader = # ???
   id    = {   type = 22000 id = 10150  }  
   Division = 
   {
    experience = 5
    id     = {   type = 22000 id = 10151   }  
    name    = "Shaanxi Mingbin" #Led by ???
    type    = militia
    model   = 1
	locked = yes
   }
 }
 # Henan (Extrapolated) Loyal to local governors/Tan Yankai. Are NOT warlodrd troops. Supported Wuhan faction.
 landunit =
 {
   location = 1322 # Luoyang
   name   = "Henan Difangjun"  
#   leader = # Tan Yankai
   id    = {   type = 22000 id = 10160  }  
   Division = 
   {
    experience = 5
    id     = {   type = 22000 id = 10161   }  
    name    = "Henan Lujun" #Led by Tan Yankai
    type    = infantry
    model   = 1
	locked = yes
   }
 }
 # Yunnan (Extrapolated)
#  landunit = 
# {
#   location = 1390 # Kunming  
#   name   = "Kunming Ye Quan Jun"  
#   leader = # ??
#   id    = {   type = 22000 id = 10170  }  
#   dormant = yes
   landdivision = 
   {
    experience = 10
    id     = {   type = 22000 id = 10171   }  
    name    = "1 YQ Division" #Led by ???
    type    = infantry  
    model   = 2
	dormant = yes
   }
   landdivision = 
   {
    experience = 10
    id     = {   type = 22000 id = 10172   }  
    name    = "2 YQ Division" #Led by ???
    type    = infantry  
    model   = 1
	dormant = yes
   }
   landdivision = 
   {
    experience = 10
    id     = {   type = 22000 id = 10173   }  
    name    = "3 YQ Division" #Led by ???
    type    = infantry  
    model   = 1
	dormant = yes
   }
# }
#  landunit = 
# {
#   location = 1292 # Ya'an 
#   name   = "Ya'an Ye Quan Jun"  
#   leader = # ??
#   id    = {   type = 22000 id = 10180  }  
#   dormant = yes
   landdivision = 
   {
    experience = 10
    id     = {   type = 22000 id = 10181   }  
    name    = "4 YQ Division" #Led by ???
    type    = infantry  
    model   = 2
	dormant = yes
   }
   landdivision = 
   {
    experience = 10
    id     = {   type = 22000 id = 10182   }  
    name    = "5 YQ Division" #Led by ???
    type    = infantry  
    model   = 1
	dormant = yes
   }
   landdivision = 
   {
    experience = 10
    id     = {   type = 22000 id = 10183   }  
    name    = "6 YQ Division" #Led by ???
    type    = infantry  
    model   = 1
	dormant = yes
   }
# }
 # Guangxi (Extrapolated) Loyal to Old Guangxi Clique
#  landunit = 
# {
#   location = 1378 # Guiling
#   name   = "Guangxi Difangjun"  
#   leader = # Lu Rongting
#   id    = {   type = 22000 id = 10190  }  
#   dormant = yes
   landdivision = 
   {
    experience = 10
    id     = {   type = 22000 id = 10191   }  
    name    = "1 GX Division" #Led by Li Zhongren
    type    = infantry  
    model   = 2
	dormant = yes
   }
   landdivision = 
   {
    experience = 10
    id     = {   type = 22000 id = 10192   }  
    name    = "2 GX Division" #Led by Lu Rongting
    type    = militia 
    model   = 1
	dormant = yes
   }
   landdivision = 
   {
    experience = 10
    id     = {   type = 22000 id = 10193   }  
    name    = "3 GX Division" #Led by ???
    type    = militia
    model   = 0
	dormant = yes
   }
# }
 # Guangdong (Extrapolated) Loyal to KMT, Sun Zhongshan
#  landunit = 
# {
#   location = 1369 # Guangzhou
#   name   = "Guangdong Difangjun"
#   leader = # Chen Jiaoming
#   id    = {   type = 22000 id = 10200  }  
#   dormant = yes
   landdivision = 
   {
    experience = 30
    id     = {   type = 22000 id = 10201   }  
    name    = "1 GD Division" #Led by Chen Jiaoming
    type    = infantry  
    model   = 2
	dormant = yes
   }
   landdivision = 
   {
    experience = 30
    id     = {   type = 22000 id = 10202   }  
    name    = "2 GD Division" #Led by ???
    type    = infantry  
    model   = 2
	dormant = yes
   }
   landdivision = 
   {
    experience = 30
    id     = {   type = 22000 id = 10203   }  
    name    = "3 GD Division" #Led by ???
    type    = infantry  
    model   = 1
	dormant = yes
   }
   landdivision = 
   {
    experience = 30
    id     = {   type = 22000 id = 10204   }  
    name    = "4 GD Division" #Led by ???
    type    = infantry  
    model   = 1
	dormant = yes
   }
# }
 # Xibei (San Ma Clique) (Extrapolated)
#  landunit = 
# {
#   location = 1264 # Lanzhou
#   name   = "1 Guyong jun"  
#   leader = # ???
#   id    = {   type = 22000 id = 10210  }  
#   dormant = yes
   landdivision = 
   {
    experience = 10
    id     = {   type = 22000 id = 10211   }  
    name    = "1 SM Guyongbin" #Led by ???
    type    = militia
    model   = 1
	dormant = yes
   }
   landdivision = 
   {
    experience = 10
    id     = {   type = 22000 id = 10212   }  
    name    = "2 SM Guyongbin" #Led by ???
    type    = militia 
    model   = 0
	dormant = yes
   }
   landdivision = 
   {
    experience = 10
    id     = {   type = 22000 id = 10213   }  
    name    = "3 SM Guyongbin" #Led by ???
    type    = militia
    model   = 0
	dormant = yes
   }
# }
#  landunit = 
# {
#   location = 1283 # Ge'ermu
#   name   = "2 Guyong jun"  
#   leader = # ???
#   id    = {   type = 22000 id = 10220  }  
#   dormant = yes
   landdivision = 
   {
    experience = 10
    id     = {   type = 22000 id = 10221   }  
    name    = "4 SM Guyongbin" #Led by ???
    type    = militia
    model   = 1
	dormant = yes
   }
   landdivision = 
   {
    experience = 10
    id     = {   type = 22000 id = 10222   }  
    name    = "5 SM Guyongbin" #Led by ???
    type    = militia 
    model   = 0
	dormant = yes
   }
   landdivision = 
   {
    experience = 10
    id     = {   type = 22000 id = 10223   }  
    name    = "6 SM Guyongbin" #Led by ???
    type    = militia
    model   = 0
	dormant = yes
   }
# }
 # Xinjiang (Extrapolated)
#  landunit = 
# {
#   location = 1281 # Urumuqi
#   name   = "Xinjiang Yuangzhenjun"  
#   leader = # ???
#   id    = {   type = 22000 id = 10230  }  
#   dormant = yes
   landdivision = 
   {
    experience = 10
    id     = {   type = 22000 id = 10231   }  
    name    = "1 Yuangzhenjun" #Led by ???
    type    = militia
    model   = 1
	dormant = yes
   }
   landdivision = 
   {
    experience = 10
    id     = {   type = 22000 id = 10232   }  
    name    = "2 Yuangzhenjun" #Led by ???
    type    = militia 
    model   = 0
	dormant = yes
   }
# }

}
