#Germany
province = { 
	id = 850 #Daar-el-Salaam
	supplypool = 10
}
province = { 
	id = 1328 #Qingdao
	supplypool = 10
	oilpool = 10
}
province = { 
	id = 883 #Lüderitz
	supplypool = 5
}
province = { 
	id = 909 #Yaounde
	supplypool = 5
}
province = { 
	id = 950 #Lome
	supplypool = 5
}
province = { 
	id = 1726 #Rabaul
	supplypool = 5
	oilpool = 5
}
#Australia
province = { 
	id = 1710 #Hobart
	supplypool = 2
}
#Belgium
province = { 
	id = 894 #Matadi
	supplypool = 3
}
#France
province = { 
	id = 728 #Oran
	supplypool = 20
}
province = { 
	id = 915 #Libreville
	supplypool = 20
}
province = { 
	id = 1002 #Tamatave
	supplypool = 2
}
province = { 
	id = 1586 #New Caledonia
	supplypool = 2
}
#Dutch East Indies
province = { 
	id = 1621 #Buru
	supplypool = 10
}
province = { 
	id = 1633 #Bandjarmasin
	supplypool = 10
}
province = { 
	id = 1638 #Bengkulu
	supplypool = 10
}
province = { 
	id = 1659 #Manado
	supplypool = 10
}
#Italy
province = { 
	id = 435 #Sassari
	supplypool = 2
}
province = { 
	id = 765 #Tobruk
	supplypool = 3
	oilpool = 3
}
province = { 
	id = 815 #Massawa
	supplypool = 2
}
province = { 
	id = 836 #Mogadishu
	supplypool = 2
}
#Japan
province = { 
	id = 1219 #Port Arthur
	supplypool = 2
}
province = { 
	id = 1232 #Busan
	supplypool = 3
}
province = { 
	id = 1362 #Taipei
	supplypool = 2
}
province = { 
	id = 1542 #Toyohara
	supplypool = 2
}
province = { 
	id = 1563 #Southern Okinawa
	supplypool = 2
}
#Portugal
province = { 
	id = 963 #Bissau
	supplypool = 5
}
province = { 
	id = 995 #Açores
	supplypool = 5
}
province = { 
	id = 994 #Madeira
	supplypool = 5
}
province = { 
	id = 895 #Luanda
	supplypool = 5
}
province = { 
	id = 1513 #Goa
	supplypool = 5
}
province = { 
	id = 855 #Moçambique
	supplypool = 5
}
province = { 
	id = 1617 #Dili
	supplypool = 5
}
province = { 
	id = 1372 #Macau
	supplypool = 5
}
#Spain
province = { 
	id = 475 #Palma de Mallorca
	supplypool = 2
}
province = { 
	id = 715 #Tangiers
	supplypool = 2
}
province = { 
	id = 990 #Canaria
	supplypool = 2
}
#Sweden
province = { 
	id = 2156 #Visby
	supplypool = 2
}
#United Kindgom
province = { 
	id = 34 #Dublin
	supplypool = 2
}
province = { 
	id = 348 #Gibraltar
	supplypool = 2
}
province = { 
	id = 429 #Malta
	supplypool = 2
}
province = { 
	id = 789 #Alexandria
	supplypool = 5
	oilpool = 5
}
province = { 
	id = 929 #Lagos
	supplypool = 2
}
province = { 
	id = 956 #Accra
	supplypool = 2
}
province = { 
	id = 964 #Freetown
	supplypool = 2
}
province = { 
	id = 997 #Port Louis
	supplypool = 2
}
province = { 
	id = 1053 #Aden
	supplypool = 2
}
province = { 
	id = 1331 #Yantai
	supplypool = 2
}
province = { 
	id = 1371 #Hong Kong
	supplypool = 2
}
province = { 
	id = 1432 #Singapore
	supplypool = 2
}
province = { 
	id = 1511 #Colombo
	supplypool = 2
	oilpool = 2
}
province = { 
	id = 2045 #Falklands
	supplypool = 2
	oilpool = 2
}
province = { 
	id = 1773 #The Bermudas
	supplypool = 2
}
#USA
province = { 
	id = 889 #Balboa
	supplypool = 5
	oilpool = 5
}
province = { 
	id = 1565 #Manila
	supplypool = 2
}
province = { 
	id = 1734 #Pearl Harbour
	supplypool = 5
	oilpool = 5
}
province = { 
	id = 1765 #Puerto Rico
	supplypool = 2
}
province = { 
	id = 1968 #Veracruz
	supplypool = 2
}
province = { 
	id = 2142 #Anchorage
	supplypool = 2
}

